### ISSUE TITLE
getting below error while running examples folder for javascript, have followed the readme file steps

### ISSUE THREAD

**Issue by yashikaraheja** [blinkcard/blinkcard-in-browser#24]
app.js:80  Failed to load SDK! DOMException: Failed to construct 'Worker': Script at 'file:///D:/node/myproject/blinkcard-in-browser/resources/BlinkCardWasmSDK.worker.min.js' cannot be accessed from origin 'null'.
    at https://cdn.jsdelivr.net/npm/@microblink/blinkcard-in-browser-sdk@2.7.0/dist/blinkcard-sdk.js:2255:32
    at new Promise (<anonymous>)
    at Object.<anonymous> (https://cdn.jsdelivr.net/npm/@microblink/blinkcard-in-browser-sdk@2.7.0/dist/blinkcard-sdk.js:2225:16)
    at Generator.next (<anonymous>)
    at https://cdn.jsdelivr.net/npm/@microblink/blinkcard-in-browser-sdk@2.7.0/dist/blinkcard-sdk.js:53:67
    at new Promise (<anonymous>)
    at __awaiter (https://cdn.jsdelivr.net/npm/@microblink/blinkcard-in-browser-sdk@2.7.0/dist/blinkcard-sdk.js:35:10)
    at Object.loadWasmModule (https://cdn.jsdelivr.net/npm/@microblink/blinkcard-in-browser-sdk@2.7.0/dist/blinkcard-sdk.js:2224:12)
    at main (file:///D:/node/myproject/blinkcard-in-browser/examples/blinkcard-camera/javascript/app.js:64:16)
    at file:///D:/node/myproject/blinkcard-in-browser/examples/blinkcard-camera/javascript/app.js:272:1

**Comment by AngTim** [comment]
Hello Yashikaraheja,

Thank you for the inquiry.
From the mentioned issue and the code snippet you have shared with us, it seems like you are not hosting the engine and worker location on the same path locally. Can you please check the following help article [https://help.microblink.com/s/direct-article?Article=ka08W000000st37QAA](url) and modify the path accordingly to have it match for engine location as it is for the worker location.

Test this approach and let me know if you have any additional questions or issues we can assist you with.

Kind regards,
Angelo
Web Support Specialist
Microblink

**Comment by yashikaraheja** [comment]
Hi, I tried hosting them on same path also, even than its not working
'{"allowHelloMessage":true,"engineLocation":"http://192.168.1.12:3000/resources","workerLocation":"http://192.168.1.12:3000/blinkcard-sdk.min.js","wasmType":null,"numberOfWorkers":null,"wasmModuleName":"BlinkCardWasmSDK","licenseKey":"sRwAAAYVZmlkZWxpdHkuY2FyZC5zY2FubmVyVKMGr01JPoEGNfvyF5adUhJAt1SGnUsMmIUjO1KwNLnqVPM8Y58SON2ZktOcYT7Y8qRlc4H8mje7DN/StQcEbnwU3C4BaAu1pMEUQOYc1Ba/NV2UeU73LyXMLznI/kWNMjuCr7hYux9yxdXT8FvI6efgs/yBCE1i2hBxWWi1R/vDnKSUs1g3xLk="}'

**Comment by AngTim** [comment]
Hello Yashikaraheja,

One of the possible reasons for this error with 'MediaDevicesNotSupported', could be due to permissions policy, and it could be helpful to try and access the application with the HTTPS protocol, as media devices can be blocked due to insecure browser context:
[https://developer.mozilla.org/en-US/docs/Web/HTTP/Permissions_Policy](url)

NotAllowedError [DOMException](https://developer.mozilla.org/en-US/docs/Web/API/DOMException)
Thrown if one or more of the requested source devices cannot be used at this time. This will happen if the browsing context is insecure (that is, the page was loaded using HTTP rather than HTTPS). It also happens if the user has specified that the current browsing instance is not permitted access to the device, the user has denied access for the current session, or the user has denied all access to user media devices globally. On browsers that support managing media permissions with [Permissions Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/Permissions_Policy), this error is returned if Permissions Policy is not configured to allow access to the input source(s).

And you can also find more about the error from our documentation: 
[https://github.com/blinkcard/blinkcard-in-browser/blob/5f2c6a486e3f0244c8cf6de0329fadd47ee2e4a1/src/MicroblinkSDK/VideoRecognizer.ts#L32C5-L32C29](url)

Kind regards,
Angelo

**Comment by yashikaraheja** [comment]
Thanks it resolved the issue in my local

**Comment by yashikaraheja** [comment]
Now i am facing another issue, i am trying to integrate in my company project which is backbone js based

i added a model class

define([], function () {
'use strict*;
const initialMessaget1 - document-getelementById("msg");
const progressEl - document.getelementById(*load-progress");
// UI elements for scanning feedback
const cameraFeed - document. getElementByld("camera-feed") 3
const cameraFeedback - document. getelementBy!Id("camera-feedback") :
const drawcontext = cameraFeedback 8& cameraFeedback.getcontext("2d") ;
const scanFeedback - document. getelementById("camera-guides*):
return FIL.Core.Model.extend ({

* Initialize and load WASM SDK.
initialize: function() {
// check if browser has proper support for WebAssembly
if (IBlinkCardsok. isBrowserSupported())
{
initialMessageEl. innerText = "This browser is not supported!";

returns;
}
// 1. It's possible to obtain a free trial license key on microblink.com
let licensekey =
*SRWAAAYVZmIkZwxpdHkuY2FyZC5zY2FubmVyVKMGr013POEGNfvyF5adUhJAt1SGnUsMmIUJO1KWNL.nqVPM8Y58SONZZktOcYT7Y8qR1c4H8mje7DN/StQcEbnwU3C4BaAU1PMEUQ0YC1Ba/NVZUeU73LyXMLZnI/kwNMjucr7hYux9yxdXT8:
if (window. location. hostname==="blinkcard.github.io”)
{
licenseKey =
"SRWAAAYTYmxpbmtjYX>kLmdpdGh1Yi5pby+N7zvPySD9Mbe+K362×H841POSUiZTDjd3UMrotMvNG40WJpwsc8vh+SYmFWkssv+Biodkzoa6iMHgneL.nPJx01p3rcRal8VRJUJ0098xSeGazX90jyjXMsDBoBm3tor+672Wr3f03Dg17u9;
if (window. location. hostname === "localhost. fidelity.co.uk")
{
licensekey =
"SRWAAAVYbG9 jYwxob3NOLmZpZGV/SaXR5LmNVLnVrIRJ j×9Ez+Mnwx5kozdG6DKP6reRszbMTfDND6p1H2rQ1AQ2a3jyACfVDNqvskbRK206n5pzN9igpdxeuuvDJsPhmQQDWhS7Av/up7AVL.11.JDz8y+8wtAQPN'mBgNJoumd+kg2GTU/OP”


Rest same code
And in index.html
I added script for cdn blinkcard

but now i am getting error that BlinkCardSDK not defined. This is for web
